version: '3.8'
services:
web:
image: nginx:latest
ports:
- "80:80"
app:
build: .
depends_on:
- db
environment:
DB_HOST: db
db:
image: mysql:latest
environment:
MYSQL_ROOT_PASSWORD: example
MYSQL_DATABASE: myapp
